/**
 * Action type string constants. These exactly match the types generated by the
 * RTK slice (whose `name` is `@schema-editor`), so consumers can listen for
 * them in their own middleware/reducers if needed.
 *
 * All types are prefixed `@schema-editor/` to avoid collisions in the host
 * store.
 */
export const SLICE_NAME = '@schema-editor';

const t = (name: string) => `${SLICE_NAME}/${name}`;

export const SchemaEditorActionTypes = {
  LOAD_SCHEMA: t('loadSchema'),
  REPLACE_SCHEMA: t('replaceSchema'),
  SET_FROM_SOURCE: t('setFromSource'),
  SELECT_NODE: t('selectNode'),
  SET_AT_POINTER: t('setAtPointer'),
  REMOVE_AT_POINTER: t('removeAtPointer'),
  RENAME_KEY: t('renameKey'),
  RENAME_DEF: t('renameDef'),
  REORDER_ARRAY: t('reorderArray'),
  TOGGLE_REQUIRED: t('toggleRequired'),
  TOGGLE_DEREFERENCE_PREVIEW: t('toggleDereferencePreview'),
  SET_SOURCE_ERROR: t('setSourceError'),
  SET_VALIDATION_ERRORS: t('setValidationErrors'),
  REMOVE_EXAMPLE_KEY: t('removeExampleKey'),
  SET_LOADING: t('setLoading'),
  MARK_SAVED: t('markSaved'),
  UNDO: t('undo'),
  REDO: t('redo'),
} as const;

export type SchemaEditorActionType =
  (typeof SchemaEditorActionTypes)[keyof typeof SchemaEditorActionTypes];
